Repository quintoandar/eslint-config-quintoandar, pull requests merged in 2019-07, with the labels that each got.

#40 [COZY-121] Create MUI imports eslint-rule
  eslint-plugin-quintoandar/rules/no-mui-import.js
  eslint-plugin-quintoandar/rules/tests/no-mui-import.test.js
Labels: review

#41 [COZY-122] Create MUI icons eslint-rule
  eslint-plugin-quintoandar/rules/no-direct-icons-import.js
  eslint-plugin-quintoandar/rules/tests/no-direct-icons-import.test.js
Labels: enhancement, review

#43 Bump lock version
  eslint-plugin-quintoandar/package-lock.json
Labels: enhancement, review

#44 Bump version with lock
  eslint-plugin-quintoandar/package-lock.json
  eslint-plugin-quintoandar/package.json
Labels: bug, review

#45 Add new rules to rules object
  eslint-plugin-quintoandar/index.js
  eslint-plugin-quintoandar/package-lock.json
  eslint-plugin-quintoandar/package.json
Labels: bug, review
