Repository quintoandar/eslint-config-quintoandar, pull requests merged in 2020-01, with the labels that each got.

#49 [ALF-219] No Block-party Login import rule
  eslint-plugin-quintoandar/rules/no-block-party-login.js
  eslint-plugin-quintoandar/rules/tests/no-block-party-login.test.js
Labels: enhancement, review

#50 [ALF-219] No Block-party Login import rule missing infos
  eslint-plugin-quintoandar/README.md
  eslint-plugin-quintoandar/index.js
  eslint-plugin-quintoandar/package-lock.json
  eslint-plugin-quintoandar/package.json
Labels: documentation, review

#51 No block-party WaffleMenu import rule
  eslint-plugin-quintoandar/README.md
  eslint-plugin-quintoandar/index.js
  eslint-plugin-quintoandar/package-lock.json
  eslint-plugin-quintoandar/package.json
  eslint-plugin-quintoandar/rules/no-block-party-waffle-menu.js
  eslint-plugin-quintoandar/rules/tests/no-block-party-waffle-menu.test.js
Labels: enhancement, review

#52 Fix waffle menu rule
  eslint-plugin-quintoandar/README.md
  eslint-plugin-quintoandar/index.js
Labels: documentation, enhancement, review
